# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsAppMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsAppMVVM

  pod 'RxSwift'
  pod 'RxCocoa'

  target 'NewsAppMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
